In [3]:
import numpy as np
import pandas as pd

terror =pd.read_csv("terrorismData.csv")
df = terror.copy()

df["Casualty"] = df["Killed"] + df["Wounded"]
casualty = df["Casualty"]

state1 = df[df["State"] == 'Jammu and Kashmir']
state2 =df[df["State"] == 'Odisha']
state3 = df[df["State"] == 'Jharkhand']
state4 = df[df["State"] == 'Andhra Pradesh']
state5 = df[df["State"] == 'Chhattisgarh']

year = len(set(df["Year"]))


casualty1 = state1['Casualty'].sum()
casualty2 = state2['Casualty'].sum()
casualty3 = state3['Casualty'].sum()
casualty4 = state4['Casualty'].sum()
casualty5 = state5['Casualty'].sum()

frequency1 = casualty1 / year

frequency2 = (casualty5 + casualty4 + casualty3 + casualty2 )/ (year)


arr = [frequency2 ,frequency1]
for i in arr:
    print(int(i), end= ' ')

261 115

In [19]:
import numpy as np
import pandas as pd

terror =pd.read_csv("terrorismData.csv")
df_terrorism = terror.copy()

year = len(set(df_terrorism["Year"]))
df_terrorism = df_terrorism[df_terrorism['Country'] == 'India']

df_terrorism['Casualty'] = df_terrorism['Killed'] + df_terrorism['Wounded']

Jammu_state = df_terrorism[df_terrorism['State'] == 'Jammu and Kashmir']

red_state = df_terrorism[(df_terrorism['State'] == 'Jharkhand')| (df_terrorism['State'] == 'Odisha') | (df_terrorism['State'] == 'Andhra Pradesh') | (df_terrorism['State'] == 'Chhatisgarh')]

red_casualty = int(np.sum(red_state['Casualty']))
jammu_casualty = int(np.sum(Jammu_state['Casualty']))

print(red_casualty//year, jammu_casualty // year)

64 261

In [2]:
import numpy as np
import pandas as pd

terror =pd.read_csv("terrorismData.csv")
df = terror.copy()

df["Casualty"] = df["Killed"] + df["Wounded"]
casualty = df["Casualty"]

state1 = df[df["State"] == 'Jammu and Kashmir']
state2 =df[df["State"] == 'Odisha']
state3 = df[df["State"] == 'Jharkhand']
state4 = df[df["State"] == 'Andhra Pradesh']
state5 = df[df["State"] == 'Chhattisgarh']

state1_casualty_sum = state1["Casualty"].sum()
state2_casualty_sum = state2["Casualty"].sum()
state3_casualty_sum = state3["Casualty"].sum()
state4_casualty_sum = state4["Casualty"].sum()
state5_casualty_sum = state5["Casualty"].sum()


year = len(set(df["Year"]))
red_corridors = state2_casualty_sum+ state3_casualty_sum +state4_casualty_sum +state5_casualty_sum
freq2 = int(red_corridors/year)
print(freq2, int(state1_casualty_sum/year))

115 261

In [18]:
import pandas as pd
import numpy as np
df=pd.read_csv("terrorismData.csv",encoding="utf8")
#df.dropna(subset=['Killed','Wounded'],inplace=True)
#df.Killed.dropna(inplace = True)
#df.Wounded.dropna(inplace = True)
ind=df[((df.State=='Jharkhand') | (df.State=='Odisha') | (df.State=='Andhra Pradesh') | (df.State=='Chhattisgarh'))]
ind1=df[df.State=='Jammu and Kashmir']
total_casuality=ind.Killed.sum()+ind.Wounded.sum()
total_casuality1=ind1.Killed.sum()+ind1.Wounded.sum()
total_freq=(total_casuality)/(47)
total_freq1=(total_casuality1)/(47)
print(int(total_freq),int(total_freq1))
len(set(df.Year))

df.Killed
df[df.Killed.isna()]

119 269

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary
15,1970,1,10,East Germany (GDR),Berlin,Eastern Europe,Berlin,52.501530,13.401851,Bombing/Explosion,NaN,NaN,Jurists Ball (Palais au Frankturm),NaN,Commune 1,Government (General),Explosives
34,1970,1,28,East Germany (GDR),Berlin,Eastern Europe,Berlin,52.501530,13.401851,Facility/Infrastructure Attack,NaN,NaN,Residence of President of Penal Office,NaN,Unknown,Police,Incendiary
95,1970,2,28,Jordan,Khalil,Middle East & North Africa,Hebron,31.530243,35.094162,Armed Assault,NaN,NaN,Tourist Bus,NaN,Unknown,Tourists,Firearms
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181636,2017,12,29,Afghanistan,Jawzjan,South Asia,Darzab district,35.974879,65.381563,Hostage Taking (Kidnapping),NaN,NaN,Religious Scholars,12/29/2017: Assailants abducted 12 religious s...,Khorasan Chapter of the Islamic State,Religious Figures/Institutions,Unknown
181640,2017,12,29,Iraq,Nineveh,Middle East & North Africa,Baaj district,36.139762,41.312916,Armed Assault,NaN,0.0,Soldiers,12/29/2017: Assailants opened fire on Iraqi Ar...,Unknown,Military,Firearms
181662,2017,12,30,Philippines,Davao Oriental,Southeast Asia,Tarragona,7.042777,126.449221,Bombing/Explosion,NaN,2.0,Soldiers,12/30/2017: Assailants opened fire on and deto...,New People's Army (NPA),Military,Explosives
181666,2017,12,30,Nigeria,Borno,Sub-Saharan Africa,Konduga district,11.492144,12.969724,Facility/Infrastructure Attack,NaN,NaN,Convoy,12/30/2017: Assailants attacked a convoy along...,Boko Haram,Private Citizens & Property,Unknown
181667,2017,12,30,Syria,Damascus,Middle East & North Africa,Harasta,33.561504,36.368763,Bombing/Explosion,NaN,NaN,Base,12/30/2017: A suicide bomber detonated an expl...,Hay'at Tahrir al-Sham,Military,Explosives

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('terrorismData.csv')
df = df.copy()
#df.dropna(inplace=True)
df["Casualty"] = df["Killed"] + df["Wounded"]
jk = df[df['State']=='Jammu and Kashmir']
red = df[(df['State']=='Jharkhand')|(df['State']=='Odisha')|(df['State']=='Andhra Pradesh')|(df['State']=='Chhattisgarh')]
df["Casualty"] = df["Killed"] + df["Wounded"]
a = red['Casualty'].sum()
b = jk['Casualty'].sum()
print(int(a/47), int(b/47))

115 261